// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AFSS.Models
{
    public partial class U1410979_AfssContext : DbContext
    {
        public U1410979_AfssContext()
        {
        }

        public U1410979_AfssContext(DbContextOptions<U1410979_AfssContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PiData> PiData { get; set; }
        public virtual DbSet<PiTask> PiTask { get; set; }
        public virtual DbSet<PiUser> PiUser { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("u1410979_afss");

            modelBuilder.Entity<PiData>(entity =>
            {
                entity.HasKey(e => e.Id)
                    .HasName("PiData_pk")
                    .IsClustered(false);

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Date).HasColumnName("date");

                entity.Property(e => e.Gas).HasColumnName("gas");

                entity.Property(e => e.PiUserId).HasColumnName("piUserId");

                entity.Property(e => e.Pressure).HasColumnName("pressure");

                entity.Property(e => e.Servo0).HasColumnName("servo0");

                entity.Property(e => e.Servo1).HasColumnName("servo1");

                entity.Property(e => e.Tmp0).HasColumnName("tmp0");

                entity.Property(e => e.Tmp1).HasColumnName("tmp1");

                entity.Property(e => e.Tmp2).HasColumnName("tmp2");

                entity.Property(e => e.Water).HasColumnName("water");

                entity.HasOne(d => d.PiUser)
                    .WithMany(p => p.PiData)
                    .HasForeignKey(d => d.PiUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("PiData_PiUser_id_fk");
            });

            modelBuilder.Entity<PiTask>(entity =>
            {
                entity.HasKey(e => e.PiKeyId)
                    .HasName("PiTask_pk")
                    .IsClustered(false);

                entity.Property(e => e.PiKeyId)
                    .ValueGeneratedNever()
                    .HasColumnName("piKeyId");

                entity.Property(e => e.Complete).HasColumnName("complete");

                entity.Property(e => e.CreateDate).HasColumnName("createDate");

                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                entity.Property(e => e.Type).HasColumnName("type");

                entity.Property(e => e.Value).HasColumnName("value");

                entity.HasOne(d => d.PiKey)
                    .WithOne(p => p.PiTask)
                    .HasForeignKey<PiTask>(d => d.PiKeyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("PiTask_PiUser_id_fk");
            });

            modelBuilder.Entity<PiUser>(entity =>
            {
                entity.HasKey(e => e.Id)
                    .HasName("PiUser_pk")
                    .IsClustered(false);

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CpuSerial)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnName("cpuSerial");

                entity.Property(e => e.Login)
                    .HasMaxLength(40)
                    .HasColumnName("login");

                entity.Property(e => e.Password)
                    .HasMaxLength(40)
                    .HasColumnName("password");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}