// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AFSS.Models
{
    public partial class PiSettings
    {
        public int Id { get; set; }
        public int PiKeyId { get; set; }
        public bool Sounds { get; set; }
        public bool Light { get; set; }
        public DateTime Date { get; set; }

        public virtual PiUser PiKey { get; set; }
    }
}