// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AFSS.Models
{
    public partial class PiTask
    {
        public int PiKeyId { get; set; }
        public DateTime CreateDate { get; set; }
        public int ServoType { get; set; }
        public int ServoValue { get; set; }
        public bool Complete { get; set; }
        public int Id { get; set; }
        public string CriticalType { get; set; }
        public string Mod { get; set; }

        public virtual PiUser PiKey { get; set; }
    }
}