@startuml
class CustomPasswordValidator {
    + RequiredLength : int <<get>> <<set>>
    + CustomPasswordValidator(length:int)
    + ValidateAsync(manager:UserManager<User>, user:User, password:string) : Task<IdentityResult>
}
class "IPasswordValidator`1"<T> {
}
"IPasswordValidator`1" "<User>" <|-- CustomPasswordValidator
@enduml
