@startuml
class LoginViewModel {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + RememberMe : bool <<get>> <<set>>
    + ReturnUrl : string <<get>> <<set>>
}
@enduml
