@startuml
class GetPiKeysController {
    + GetPiKeysController(afssDbContext:AfssContext, applicationContext:ApplicationContext)
    + Index() : IEnumerable<PiKey>
}
Controller <|-- GetPiKeysController
@enduml
