@startuml
class HomeController {
    + HomeController(logger:ILogger<HomeController>)
    + Index() : IActionResult
    + Privacy() : IActionResult
    + Error() : IActionResult
}
Controller <|-- HomeController
@enduml
