@startuml
class UpdateKeyController {
    + UpdateKeyController(afssDbContext:AfssContext, applicationContext:ApplicationContext)
    + Index(PiKey:string) : void
}
Controller <|-- UpdateKeyController
@enduml
