@startuml
!include .\\Program.puml
!include .\\Controllers\AccountController.puml
!include .\\Controllers\DataUserController.puml
!include .\\Controllers\FooterController.puml
!include .\\Controllers\GetDataController.puml
!include .\\Controllers\GetInfoUserController.puml
!include .\\Controllers\GetPiKeysController.puml
!include .\\Controllers\GetPiSettingsController.puml
!include .\\Controllers\GetThresholdsController.puml
!include .\\Controllers\HomeController.puml
!include .\\Controllers\InformationsController.puml
!include .\\Controllers\MenuController.puml
!include .\\Controllers\MenuInputController.puml
!include .\\Controllers\SelectionController.puml
!include .\\Controllers\SettingsController.puml
!include .\\Controllers\StatisticsController.puml
!include .\\Controllers\SubMenuController.puml
!include .\\Controllers\TaskCreateController.puml
!include .\\Controllers\ThresholdsController.puml
!include .\\Controllers\UpdateController.puml
!include .\\Controllers\UpdateKeyController.puml
!include .\\Controllers\UpdatePiSettingsController.puml
!include .\\Controllers\UpdateThresholdsController.puml
!include .\\Controllers\VerifyThresholdsController.puml
!include .\\Migrations\20220223161422_Init.puml
!include .\\Migrations\20220223161422_Init.Designer.puml
!include .\\Migrations\20220227192832_changePiKeyToString.puml
!include .\\Migrations\20220227192832_changePiKeyToString.Designer.puml
!include .\\Migrations\ApplicationContextModelSnapshot.puml
!include .\\Models\AfssContext.puml
!include .\\Models\ApplicationContext.puml
!include .\\Models\ErrorViewModel.puml
!include .\\Models\PiData.puml
!include .\\Models\PiKey.puml
!include .\\Models\PiSettings.puml
!include .\\Models\PiTask.puml
!include .\\Models\PiTaskDTO.puml
!include .\\Models\PiTaskType.puml
!include .\\Models\PiThresholds.puml
!include .\\Models\PiThresholdsDTO.puml
!include .\\Models\PiUser.puml
!include .\\Models\User.puml
!include .\\Models\UserDTO.puml
!include .\\Services\EmailService.puml
!include .\\Services\ISmsService.puml
!include .\\Services\SmsAeroService.puml
!include .\\Validators\CustomEmailValidator.puml
!include .\\Validators\CustomNameValidator.puml
!include .\\Validators\CustomNewPasswordValidator.puml
!include .\\Validators\CustomPasswordValidator.puml
!include .\\Validators\CustomPhoneValidator.puml
!include .\\Validators\CustomRegisrationValidator.puml
!include .\\Validators\ObserveValidator.puml
!include .\\ViewModels\ChangeRoleViewModel.puml
!include .\\ViewModels\DataUserViewModel.puml
!include .\\ViewModels\EmailViewModel.puml
!include .\\ViewModels\LoginViewModel.puml
!include .\\ViewModels\MenuViewModel.puml
!include .\\ViewModels\NameViewModel.puml
!include .\\ViewModels\ObserveViewModel.puml
!include .\\ViewModels\PasswordViewModel.puml
!include .\\ViewModels\PhoneViewModel.puml
!include .\\ViewModels\RegisterViewModel.puml
!include .\\ViewModels\ThresholdsViewModel.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\AFSS.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\AFSS.GlobalUsings.g.puml
!include .\\obj\Debug\net6.0\AFSS.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Debug\net6.0\AFSS.RazorAssemblyInfo.puml
!include .\\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Release\net6.0\AFSS.AssemblyInfo.puml
!include .\\obj\Release\net6.0\AFSS.GlobalUsings.g.puml
!include .\\obj\Release\net6.0\AFSS.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Release\net6.0\AFSS.RazorAssemblyInfo.puml
@enduml
